MiguelCastillo/bit-loader

Gruntfile.js
dist/bit-loader.js
package.json
src/bit-loader.js
src/loader.js
src/meta/compilation.js
src/meta/dependencies.js
src/meta/fetch.js
src/meta/transform.js
src/meta/validation.js
src/module/linker.js
src/pipeline.js
tests/SpecRunner.js
tests/config.js
tests/specs/loader.js

- Also to break out the fetch interface out of the module loading
pipeline

Invasive refactor to cleanup how pipeline assets are defined

---

.eslintrc
src/bit-loader.js
src/meta/dependency.js
src/meta/transform.js
src/middleware.js
src/plugin.js
src/rule-matcher.js
test/spec/plugin.js

Big PR to add support for a way to register plugins into the transform and dependency life cycle of the module loading process. Plugins can also be configured with glob pattern matching for determining a particular plugin can process a module.

Plugin pipelines

---

example/bundler-plugin/index.js
src/loader.js
src/meta/resolve.js
src/plugin.js
test/spec/ignore.js
test/spec/loader.js
test/spec/plugin.js

https://github.com/MiguelCastillo/bit-loader/issues/102

adding support for resolve as plugin

---

.jshintrc
src/logger.js

- added serialize method to configure how messages are serialized
before they are written to the stream.
- added a way to set a default stream and a default serializer

refactored logger so that it can write to streams.

---

example/asyncfile/compiler.js
example/asyncfile/index.js
example/asyncfile/resolvePath.js
example/babel-plugin/index.js
example/babel-plugin/src/fileReader.js
example/babel-plugin/src/pstream.js
example/babel-plugin/src/resolvePath.js
example/bundler-plugin/index.js
example/bundler-plugin/src/fileReader.js
example/package.json
src/meta/resolve.js
src/plugin.js

https://github.com/MiguelCastillo/bit-loader/issues/118

refactored deferred plugin handler to simplify the code

---

src/module.js

https://github.com/MiguelCastillo/bit-loader/issues/125

removed Module settings

---

src/bit-loader.js
src/plugin.js
test/spec/plugin.js

bit loader is now using the visitor hook to add deferred plugins to the
ignore list.
https://github.com/MiguelCastillo/bit-loader/issues/129

added visitor hook when configuring plugins

---

src/bit-loader.js
src/loader.js
src/meta/dependency.js

https://github.com/MiguelCastillo/bit-loader/issues/134

changed parentMeta to module referer

---

src/plugin.js

https://github.com/MiguelCastillo/bit-loader/issues/181

Added a `then` to handle async plugin execution

---

src/bit-loader.js
src/plugin.js

https://github.com/MiguelCastillo/bit-loader/issues/199

added ability to pass plugin coffins with name

---

src/bit-loader.js
test/spec/bit-loader.js

https://github.com/MiguelCastillo/bit-loader/issues/201

Added ability to specify more complex objects similar to plugins

---

src/controllers/builder.js

currently, source mapped can end up in the wrong location.

improved source url for better source mapping

---

src/bit-loader.js
src/controllers/fetcher.js

fetchOnly is useful for preloading a cache with source that is later processed

Added method for fetching source files without processing it

---

src/controllers/fetcher.js
src/module.js
test/spec/build.js

https://github.com/MiguelCastillo/bit-loader/issues/219

Fixed issue with deferred module processing

---

README.md
src/bit-loader.js
src/controllers/fetcher.js
src/services/precompile.js
test/spec/fetch.js

use case: https://github.com/MiguelCastillo/bit-loader/issues/186

Added precompile pipeline and added corresponding readme docs

---

src/plugin/plugin.js
src/plugin/registrar.js
test/spec/plugin/plugin.js

https://github.com/MiguelCastillo/bit-loader/issues/238

Preemptively load all plugins before processing application code

---

src/matches.js
test/spec/matches.js

https://github.com/MiguelCastillo/bit-loader/issues/253

Fixed logic for configuring multiple matching criteria in a single rule

---

src/controllers/helpers.js
test/spec/bit-loader.js
test/spec/fetch.js

https://github.com/MiguelCastillo/bit-loader/issues/260

Changed the order in which modules are committed to the cache

---

README.md

Updated plugin handler description

---

README.md

Adjusted some of the language for Plugins to be a lil bit more clear

---

src/controllers/fetcher.js

https://github.com/MiguelCastillo/bit-loader/issues/269

Added logic for loading modules only when they are in resolve state

---

src/bit-loader.js

https://github.com/MiguelCastillo/bit-loader/issues/287

fixing issue with plugin functions getting properly processed

---

package.json

fix(package): update belty to version 5.0.1

---

package.json

chore(package): update belty to version 5.0.3
